-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_demosaic_0_0_DebayerG is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    imgBayer_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    imgBayer_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgBayer_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgBayer_empty_n : IN STD_LOGIC;
    imgBayer_read : OUT STD_LOGIC;
    imgG_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    imgG_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgG_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgG_full_n : IN STD_LOGIC;
    imgG_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c9_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c9_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c9_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c9_full_n : IN STD_LOGIC;
    bayerPhase_c9_write : OUT STD_LOGIC );
end;


architecture behav of design_1_v_demosaic_0_0_DebayerG is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv17_1FFFE : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal bayerPhase_c9_blk_n : STD_LOGIC;
    signal zext_ln229_fu_266_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln229_reg_552 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopHeight_fu_270_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopHeight_reg_557 : STD_LOGIC_VECTOR (16 downto 0);
    signal x_phase_fu_280_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_reg_562 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln248_1_reg_567 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln270_fu_294_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln270_reg_573 : STD_LOGIC_VECTOR (16 downto 0);
    signal y_7_reg_578 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_0_0_038836808_lcssa6865_load_reg_588 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln270_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_0_03883_167406813_lcssa6867_load_reg_593 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_267446816_lcssa6869_load_reg_598 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_16819_lcssa6871_load_reg_603 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_1_16824_lcssa6873_load_reg_608 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_1_26827_lcssa6875_load_reg_613 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_26830_lcssa6877_load_reg_618 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_2_16835_lcssa6879_load_reg_623 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_2_26838_lcssa6881_load_reg_628 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_36841_lcssa6883_load_reg_633 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_3_16846_lcssa6885_load_reg_638 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_3_26849_lcssa6887_load_reg_643 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_46852_lcssa6889_load_reg_648 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_4_16857_lcssa6891_load_reg_653 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_4_26860_lcssa6893_load_reg_658 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69937010_load_reg_663 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69947012_load_reg_668 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69957014_load_reg_673 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69967016_load_reg_678 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03875_46989_lcssa69987018_load_reg_683 : STD_LOGIC_VECTOR (9 downto 0);
    signal cmp84_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp84_reg_688 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_y_fu_392_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal out_y_reg_693 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal xor_fu_402_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_reg_698 : STD_LOGIC_VECTOR (14 downto 0);
    signal cmp724_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp724_reg_703 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp170_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp170_reg_708 : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf_yuv_val_V_q1 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_yuv_val_V_1_q1 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_yuv_val_V_2_q1 : STD_LOGIC_VECTOR (9 downto 0);
    signal linebuf_yuv_val_V_3_q1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_idle : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_ready : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgBayer_read : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_write : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03875_469896997_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03875_469896997_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out1_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out2_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out3_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_26859_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_26859_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_16856_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_16856_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_46851_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_46851_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_26848_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_26848_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_16845_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_16845_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_36840_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_36840_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_26837_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_26837_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_16834_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_16834_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_26829_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_26829_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_26826_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_26826_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_16823_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_16823_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_16818_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_16818_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_267446815_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_267446815_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_167406812_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_167406812_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_038836807_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_038836807_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_0_03875_46989_lcssa69987018_fu_156 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69967016_fu_152 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69957014_fu_148 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69947012_fu_144 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa69937010_fu_140 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_4_26860_lcssa6893_fu_136 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_4_16857_lcssa6891_fu_132 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_46852_lcssa6889_fu_128 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_3_26849_lcssa6887_fu_124 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_3_16846_lcssa6885_fu_120 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_36841_lcssa6883_fu_116 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_2_26838_lcssa6881_fu_112 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_2_16835_lcssa6879_fu_108 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_26830_lcssa6877_fu_104 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_1_26827_lcssa6875_fu_100 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_1_16824_lcssa6873_fu_96 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_16819_lcssa6871_fu_92 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_267446816_lcssa6869_fu_88 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_03883_167406813_lcssa6867_fu_84 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_038836808_lcssa6865_fu_80 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_76 : STD_LOGIC_VECTOR (16 downto 0);
    signal y_8_fu_313_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal zext_ln238_fu_276_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_132_fu_389_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and261_cast_fu_398_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_273_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgBayer_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        imgBayer_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgBayer_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgBayer_empty_n : IN STD_LOGIC;
        imgBayer_read : OUT STD_LOGIC;
        imgG_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        imgG_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgG_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgG_full_n : IN STD_LOGIC;
        imgG_write : OUT STD_LOGIC;
        p_0_0_03875_46989_lcssa69987018 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa69967016 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa69957014 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa69947012 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa69937010 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_4_26860_lcssa6893 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_4_16857_lcssa6891 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_46852_lcssa6889 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_3_26849_lcssa6887 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_3_16846_lcssa6885 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_36841_lcssa6883 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_2_26838_lcssa6881 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_2_16835_lcssa6879 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_26830_lcssa6877 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_1_26827_lcssa6875 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_1_16824_lcssa6873 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_16819_lcssa6871 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_267446816_lcssa6869 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_167406813_lcssa6867 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_038836808_lcssa6865 : IN STD_LOGIC_VECTOR (9 downto 0);
        add_ln270 : IN STD_LOGIC_VECTOR (16 downto 0);
        x_phase : IN STD_LOGIC_VECTOR (0 downto 0);
        xor_r : IN STD_LOGIC_VECTOR (14 downto 0);
        cmp724 : IN STD_LOGIC_VECTOR (0 downto 0);
        out_y : IN STD_LOGIC_VECTOR (16 downto 0);
        linebuf_yuv_val_V_3_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_3_ce0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_3_we0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_3_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_yuv_val_V_3_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_3_ce1 : OUT STD_LOGIC;
        linebuf_yuv_val_V_3_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        linebuf_yuv_val_V_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_2_ce0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_2_we0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_2_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_yuv_val_V_2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_2_ce1 : OUT STD_LOGIC;
        linebuf_yuv_val_V_2_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        linebuf_yuv_val_V_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_1_ce0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_1_we0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_yuv_val_V_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_1_ce1 : OUT STD_LOGIC;
        linebuf_yuv_val_V_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        linebuf_yuv_val_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_ce0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_we0 : OUT STD_LOGIC;
        linebuf_yuv_val_V_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        linebuf_yuv_val_V_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        linebuf_yuv_val_V_ce1 : OUT STD_LOGIC;
        linebuf_yuv_val_V_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        zext_ln238 : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp170 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp84 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_0_0_03875_469896997_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03875_469896997_out_ap_vld : OUT STD_LOGIC;
        p_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_4_26859_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_4_26859_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_4_16856_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_4_16856_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_46851_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_46851_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_3_26848_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_3_26848_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_3_16845_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_3_16845_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_36840_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_36840_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_2_26837_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_2_26837_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_2_16834_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_2_16834_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_26829_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_26829_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_1_26826_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_1_26826_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_1_16823_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_1_16823_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_16818_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_16818_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_267446815_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_267446815_out_ap_vld : OUT STD_LOGIC;
        p_0_0_03883_167406812_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_03883_167406812_out_ap_vld : OUT STD_LOGIC;
        p_0_0_038836807_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_038836807_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (9 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    linebuf_yuv_val_V_U : component design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 10,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce1,
        q1 => linebuf_yuv_val_V_q1);

    linebuf_yuv_val_V_1_U : component design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 10,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce1,
        q1 => linebuf_yuv_val_V_1_q1);

    linebuf_yuv_val_V_2_U : component design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 10,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce1,
        q1 => linebuf_yuv_val_V_2_q1);

    linebuf_yuv_val_V_3_U : component design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 10,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce1,
        q1 => linebuf_yuv_val_V_3_q1);

    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202 : component design_1_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_273_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start,
        ap_done => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done,
        ap_idle => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_idle,
        ap_ready => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_ready,
        imgBayer_dout => imgBayer_dout,
        imgBayer_num_data_valid => imgBayer_num_data_valid,
        imgBayer_fifo_cap => ap_const_lv2_0,
        imgBayer_empty_n => imgBayer_empty_n,
        imgBayer_read => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgBayer_read,
        imgG_din => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_din,
        imgG_num_data_valid => ap_const_lv2_0,
        imgG_fifo_cap => ap_const_lv2_0,
        imgG_full_n => imgG_full_n,
        imgG_write => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_write,
        p_0_0_03875_46989_lcssa69987018 => p_0_0_03875_46989_lcssa69987018_load_reg_683,
        p_lcssa69967016 => p_lcssa69967016_load_reg_678,
        p_lcssa69957014 => p_lcssa69957014_load_reg_673,
        p_lcssa69947012 => p_lcssa69947012_load_reg_668,
        p_lcssa69937010 => p_lcssa69937010_load_reg_663,
        p_0_0_03883_4_26860_lcssa6893 => p_0_0_03883_4_26860_lcssa6893_load_reg_658,
        p_0_0_03883_4_16857_lcssa6891 => p_0_0_03883_4_16857_lcssa6891_load_reg_653,
        p_0_0_03883_46852_lcssa6889 => p_0_0_03883_46852_lcssa6889_load_reg_648,
        p_0_0_03883_3_26849_lcssa6887 => p_0_0_03883_3_26849_lcssa6887_load_reg_643,
        p_0_0_03883_3_16846_lcssa6885 => p_0_0_03883_3_16846_lcssa6885_load_reg_638,
        p_0_0_03883_36841_lcssa6883 => p_0_0_03883_36841_lcssa6883_load_reg_633,
        p_0_0_03883_2_26838_lcssa6881 => p_0_0_03883_2_26838_lcssa6881_load_reg_628,
        p_0_0_03883_2_16835_lcssa6879 => p_0_0_03883_2_16835_lcssa6879_load_reg_623,
        p_0_0_03883_26830_lcssa6877 => p_0_0_03883_26830_lcssa6877_load_reg_618,
        p_0_0_03883_1_26827_lcssa6875 => p_0_0_03883_1_26827_lcssa6875_load_reg_613,
        p_0_0_03883_1_16824_lcssa6873 => p_0_0_03883_1_16824_lcssa6873_load_reg_608,
        p_0_0_03883_16819_lcssa6871 => p_0_0_03883_16819_lcssa6871_load_reg_603,
        p_0_0_03883_267446816_lcssa6869 => p_0_0_03883_267446816_lcssa6869_load_reg_598,
        p_0_0_03883_167406813_lcssa6867 => p_0_0_03883_167406813_lcssa6867_load_reg_593,
        p_0_0_038836808_lcssa6865 => p_0_0_038836808_lcssa6865_load_reg_588,
        add_ln270 => add_ln270_reg_573,
        x_phase => x_phase_reg_562,
        xor_r => xor_reg_698,
        cmp724 => cmp724_reg_703,
        out_y => out_y_reg_693,
        linebuf_yuv_val_V_3_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address0,
        linebuf_yuv_val_V_3_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce0,
        linebuf_yuv_val_V_3_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_we0,
        linebuf_yuv_val_V_3_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_d0,
        linebuf_yuv_val_V_3_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address1,
        linebuf_yuv_val_V_3_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce1,
        linebuf_yuv_val_V_3_q1 => linebuf_yuv_val_V_3_q1,
        linebuf_yuv_val_V_2_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address0,
        linebuf_yuv_val_V_2_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce0,
        linebuf_yuv_val_V_2_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_we0,
        linebuf_yuv_val_V_2_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_d0,
        linebuf_yuv_val_V_2_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address1,
        linebuf_yuv_val_V_2_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce1,
        linebuf_yuv_val_V_2_q1 => linebuf_yuv_val_V_2_q1,
        linebuf_yuv_val_V_1_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address0,
        linebuf_yuv_val_V_1_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce0,
        linebuf_yuv_val_V_1_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_we0,
        linebuf_yuv_val_V_1_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_d0,
        linebuf_yuv_val_V_1_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address1,
        linebuf_yuv_val_V_1_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce1,
        linebuf_yuv_val_V_1_q1 => linebuf_yuv_val_V_1_q1,
        linebuf_yuv_val_V_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address0,
        linebuf_yuv_val_V_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce0,
        linebuf_yuv_val_V_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_we0,
        linebuf_yuv_val_V_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_d0,
        linebuf_yuv_val_V_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address1,
        linebuf_yuv_val_V_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce1,
        linebuf_yuv_val_V_q1 => linebuf_yuv_val_V_q1,
        zext_ln238 => width,
        cmp170 => cmp170_reg_708,
        cmp84 => cmp84_reg_688,
        p_0_0_03875_469896997_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03875_469896997_out,
        p_0_0_03875_469896997_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03875_469896997_out_ap_vld,
        p_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out,
        p_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out_ap_vld,
        p_out1 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out1,
        p_out1_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out1_ap_vld,
        p_out2 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out2,
        p_out2_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out2_ap_vld,
        p_out3 => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out3,
        p_out3_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out3_ap_vld,
        p_0_0_03883_4_26859_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_26859_out,
        p_0_0_03883_4_26859_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_26859_out_ap_vld,
        p_0_0_03883_4_16856_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_16856_out,
        p_0_0_03883_4_16856_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_16856_out_ap_vld,
        p_0_0_03883_46851_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_46851_out,
        p_0_0_03883_46851_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_46851_out_ap_vld,
        p_0_0_03883_3_26848_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_26848_out,
        p_0_0_03883_3_26848_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_26848_out_ap_vld,
        p_0_0_03883_3_16845_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_16845_out,
        p_0_0_03883_3_16845_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_16845_out_ap_vld,
        p_0_0_03883_36840_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_36840_out,
        p_0_0_03883_36840_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_36840_out_ap_vld,
        p_0_0_03883_2_26837_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_26837_out,
        p_0_0_03883_2_26837_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_26837_out_ap_vld,
        p_0_0_03883_2_16834_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_16834_out,
        p_0_0_03883_2_16834_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_16834_out_ap_vld,
        p_0_0_03883_26829_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_26829_out,
        p_0_0_03883_26829_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_26829_out_ap_vld,
        p_0_0_03883_1_26826_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_26826_out,
        p_0_0_03883_1_26826_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_26826_out_ap_vld,
        p_0_0_03883_1_16823_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_16823_out,
        p_0_0_03883_1_16823_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_16823_out_ap_vld,
        p_0_0_03883_16818_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_16818_out,
        p_0_0_03883_16818_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_16818_out_ap_vld,
        p_0_0_03883_267446815_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_267446815_out,
        p_0_0_03883_267446815_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_267446815_out_ap_vld,
        p_0_0_03883_167406812_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_167406812_out,
        p_0_0_03883_167406812_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_167406812_out_ap_vld,
        p_0_0_038836807_out => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_038836807_out,
        p_0_0_038836807_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_038836807_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln270_fu_308_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((bayerPhase_c9_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_76 <= ap_const_lv17_0;
            elsif (((icmp_ln270_fu_308_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_76 <= y_8_fu_313_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln270_reg_573 <= add_ln270_fu_294_p2;
                loopHeight_reg_557 <= loopHeight_fu_270_p2;
                trunc_ln248_1_reg_567 <= p_read(15 downto 1);
                x_phase_reg_562 <= x_phase_fu_280_p1;
                    zext_ln229_reg_552(15 downto 0) <= zext_ln229_fu_266_p1(15 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                cmp170_reg_708 <= cmp170_fu_414_p2;
                cmp724_reg_703 <= cmp724_fu_408_p2;
                out_y_reg_693 <= out_y_fu_392_p2;
                xor_reg_698 <= xor_fu_402_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln270_fu_308_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                cmp84_reg_688 <= cmp84_fu_379_p2;
                p_0_0_03875_46989_lcssa69987018_load_reg_683 <= p_0_0_03875_46989_lcssa69987018_fu_156;
                p_0_0_038836808_lcssa6865_load_reg_588 <= p_0_0_038836808_lcssa6865_fu_80;
                p_0_0_03883_167406813_lcssa6867_load_reg_593 <= p_0_0_03883_167406813_lcssa6867_fu_84;
                p_0_0_03883_16819_lcssa6871_load_reg_603 <= p_0_0_03883_16819_lcssa6871_fu_92;
                p_0_0_03883_1_16824_lcssa6873_load_reg_608 <= p_0_0_03883_1_16824_lcssa6873_fu_96;
                p_0_0_03883_1_26827_lcssa6875_load_reg_613 <= p_0_0_03883_1_26827_lcssa6875_fu_100;
                p_0_0_03883_267446816_lcssa6869_load_reg_598 <= p_0_0_03883_267446816_lcssa6869_fu_88;
                p_0_0_03883_26830_lcssa6877_load_reg_618 <= p_0_0_03883_26830_lcssa6877_fu_104;
                p_0_0_03883_2_16835_lcssa6879_load_reg_623 <= p_0_0_03883_2_16835_lcssa6879_fu_108;
                p_0_0_03883_2_26838_lcssa6881_load_reg_628 <= p_0_0_03883_2_26838_lcssa6881_fu_112;
                p_0_0_03883_36841_lcssa6883_load_reg_633 <= p_0_0_03883_36841_lcssa6883_fu_116;
                p_0_0_03883_3_16846_lcssa6885_load_reg_638 <= p_0_0_03883_3_16846_lcssa6885_fu_120;
                p_0_0_03883_3_26849_lcssa6887_load_reg_643 <= p_0_0_03883_3_26849_lcssa6887_fu_124;
                p_0_0_03883_46852_lcssa6889_load_reg_648 <= p_0_0_03883_46852_lcssa6889_fu_128;
                p_0_0_03883_4_16857_lcssa6891_load_reg_653 <= p_0_0_03883_4_16857_lcssa6891_fu_132;
                p_0_0_03883_4_26860_lcssa6893_load_reg_658 <= p_0_0_03883_4_26860_lcssa6893_fu_136;
                p_lcssa69937010_load_reg_663 <= p_lcssa69937010_fu_140;
                p_lcssa69947012_load_reg_668 <= p_lcssa69947012_fu_144;
                p_lcssa69957014_load_reg_673 <= p_lcssa69957014_fu_148;
                p_lcssa69967016_load_reg_678 <= p_lcssa69967016_fu_152;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03875_469896997_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03875_46989_lcssa69987018_fu_156 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03875_469896997_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_038836807_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_038836808_lcssa6865_fu_80 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_038836807_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_167406812_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_167406813_lcssa6867_fu_84 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_167406812_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_16818_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_16819_lcssa6871_fu_92 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_16818_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_16823_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_1_16824_lcssa6873_fu_96 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_16823_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_26826_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_1_26827_lcssa6875_fu_100 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_1_26826_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_267446815_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_267446816_lcssa6869_fu_88 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_267446815_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_26829_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_26830_lcssa6877_fu_104 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_26829_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_16834_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_2_16835_lcssa6879_fu_108 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_16834_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_26837_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_2_26838_lcssa6881_fu_112 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_2_26837_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_36840_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_36841_lcssa6883_fu_116 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_36840_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_16845_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_3_16846_lcssa6885_fu_120 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_16845_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_26848_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_3_26849_lcssa6887_fu_124 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_3_26848_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_46851_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_46852_lcssa6889_fu_128 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_46851_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_16856_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_4_16857_lcssa6891_fu_132 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_16856_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_26859_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_03883_4_26860_lcssa6893_fu_136 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_0_0_03883_4_26859_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa69937010_fu_140 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa69947012_fu_144 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa69957014_fu_148 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa69967016_fu_152 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y_7_reg_578 <= y_fu_76;
            end if;
        end if;
    end process;
    zext_ln229_reg_552(16) <= '0';

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, bayerPhase_c9_full_n, ap_CS_fsm_state2, icmp_ln270_fu_308_p2, grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((bayerPhase_c9_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln270_fu_308_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln270_fu_294_p2 <= std_logic_vector(unsigned(zext_ln238_fu_276_p1) + unsigned(ap_const_lv17_2));
    and261_cast_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_132_fu_389_p1),15));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, bayerPhase_c9_full_n)
    begin
        if (((bayerPhase_c9_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done)
    begin
        if ((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, bayerPhase_c9_full_n)
    begin
                ap_block_state1 <= ((bayerPhase_c9_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln270_fu_308_p2)
    begin
        if (((icmp_ln270_fu_308_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bayerPhase_c9_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c9_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c9_blk_n <= bayerPhase_c9_full_n;
        else 
            bayerPhase_c9_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bayerPhase_c9_din <= p_read;

    bayerPhase_c9_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c9_full_n)
    begin
        if ((not(((bayerPhase_c9_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c9_write <= ap_const_logic_1;
        else 
            bayerPhase_c9_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp170_fu_414_p2 <= "0" when (y_7_reg_578 = ap_const_lv17_0) else "1";
    cmp724_fu_408_p2 <= "1" when (and261_cast_fu_398_p1 = trunc_ln248_1_reg_567) else "0";
    cmp84_fu_379_p2 <= "1" when (unsigned(y_fu_76) < unsigned(zext_ln229_reg_552)) else "0";
    empty_132_fu_389_p1 <= y_7_reg_578(1 - 1 downto 0);
    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg;
    icmp_ln270_fu_308_p2 <= "1" when (y_fu_76 = loopHeight_reg_557) else "0";

    imgBayer_read_assign_proc : process(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgBayer_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            imgBayer_read <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgBayer_read;
        else 
            imgBayer_read <= ap_const_logic_0;
        end if; 
    end process;

    imgG_din <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_din;

    imgG_write_assign_proc : process(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            imgG_write <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_write;
        else 
            imgG_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln270_fu_308_p2)
    begin
        if (((icmp_ln270_fu_308_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_fu_270_p2 <= std_logic_vector(unsigned(zext_ln229_fu_266_p1) + unsigned(ap_const_lv17_2));
    out_y_fu_392_p2 <= std_logic_vector(unsigned(y_7_reg_578) + unsigned(ap_const_lv17_1FFFE));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    x_phase_fu_280_p1 <= p_read(1 - 1 downto 0);
    xor_fu_402_p2 <= (trunc_ln248_1_reg_567 xor and261_cast_fu_398_p1);
    y_8_fu_313_p2 <= std_logic_vector(unsigned(y_fu_76) + unsigned(ap_const_lv17_1));
    zext_ln229_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),17));
    zext_ln238_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),17));
end behav;
