-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_demosaic_0_0_DebayerRatBorBatR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    imgG_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    imgG_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgG_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgG_empty_n : IN STD_LOGIC;
    imgG_read : OUT STD_LOGIC;
    imgRB_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    imgRB_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgRB_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgRB_full_n : IN STD_LOGIC;
    imgRB_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (10 downto 0);
    width : IN STD_LOGIC_VECTOR (10 downto 0);
    bayerPhase_c9_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c9_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c9_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c9_empty_n : IN STD_LOGIC;
    bayerPhase_c9_read : OUT STD_LOGIC;
    bayerPhase_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c_full_n : IN STD_LOGIC;
    bayerPhase_c_write : OUT STD_LOGIC );
end;


architecture behav of design_1_v_demosaic_0_0_DebayerRatBorBatR is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal bayerPhase_c9_blk_n : STD_LOGIC;
    signal bayerPhase_c_blk_n : STD_LOGIC;
    signal loopHeight_fu_222_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopHeight_reg_488 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_phase_fu_228_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_reg_493 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln577_1_i_reg_498 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln585_fu_242_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln585_reg_504 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln585_fu_256_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln585_reg_509 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_0_0_0_0_010752214_lcssa2266_i_load_reg_517 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln585_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_1_0_0_010762217_lcssa2268_i_load_reg_522 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_010772220_lcssa2270_i_load_reg_527 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_01075_22244_lcssa2278_i_load_reg_532 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_01076_22247_lcssa2280_i_load_reg_537 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_01077_22250_lcssa2282_i_load_reg_542 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_010382303_lcssa2337_i_load_reg_547 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_010392305_lcssa2339_i_load_reg_552 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_010402307_lcssa2341_i_load_reg_557 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa23092343_i_load_reg_562 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa23102345_i_load_reg_567 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa23112347_i_load_reg_572 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01074_222932312_lcssa2349_i_load_reg_577 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01073_222952314_lcssa2351_i_load_reg_582 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01072_222972316_lcssa2353_i_load_reg_587 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_126_fu_316_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_126_reg_592 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp58_i_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp58_i_reg_597 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp202_i_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp202_i_reg_602 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_y_i_fu_336_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal out_y_i_reg_607 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal xor_i_fu_351_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_i_reg_612 : STD_LOGIC_VECTOR (14 downto 0);
    signal red_i_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal red_i_reg_617 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_127_fu_363_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_127_reg_622 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_128_fu_372_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_128_reg_627 : STD_LOGIC_VECTOR (1 downto 0);
    signal lineBuffer_val_V_q1 : STD_LOGIC_VECTOR (29 downto 0);
    signal lineBuffer_val_V_1_q1 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_idle : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_ready : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgG_read : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_write : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_we0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_d0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce1 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_we0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_d0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce1 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_red_i : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_0_01072_222972316_lcssa2353_i_fu_134 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01073_222952314_lcssa2351_i_fu_130 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01074_222932312_lcssa2349_i_fu_126 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa23112347_i_fu_122 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa23102345_i_fu_118 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa23092343_i_fu_114 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_010402307_lcssa2341_i_fu_110 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_010392305_lcssa2339_i_fu_106 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_010382303_lcssa2337_i_fu_102 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_01077_22250_lcssa2282_i_fu_98 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_01076_22247_lcssa2280_i_fu_94 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_01075_22244_lcssa2278_i_fu_90 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_010772220_lcssa2270_i_fu_86 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_010762217_lcssa2268_i_fu_82 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_010752214_lcssa2266_i_fu_78 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_74 : STD_LOGIC_VECTOR (10 downto 0);
    signal y_4_fu_265_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal out_y_cast_i_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and309_cast_i_fu_347_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgG_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        imgG_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgG_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgG_empty_n : IN STD_LOGIC;
        imgG_read : OUT STD_LOGIC;
        imgRB_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        imgRB_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgRB_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgRB_full_n : IN STD_LOGIC;
        imgRB_write : OUT STD_LOGIC;
        p_0_0_01072_222972316_lcssa2353_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01073_222952314_lcssa2351_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01074_222932312_lcssa2349_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa23112347_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa23102345_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa23092343_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_010402307_lcssa2341_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_010392305_lcssa2339_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_010382303_lcssa2337_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_01077_22250_lcssa2282_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_01076_22247_lcssa2280_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_01075_22244_lcssa2278_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_010772220_lcssa2270_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_010762217_lcssa2268_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_010752214_lcssa2266_i : IN STD_LOGIC_VECTOR (9 downto 0);
        add_ln585_i : IN STD_LOGIC_VECTOR (10 downto 0);
        out_y_i : IN STD_LOGIC_VECTOR (11 downto 0);
        x_phase_i : IN STD_LOGIC_VECTOR (0 downto 0);
        xor_i : IN STD_LOGIC_VECTOR (14 downto 0);
        lineBuffer_val_V_1_i_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_1_i_ce0 : OUT STD_LOGIC;
        lineBuffer_val_V_1_i_we0 : OUT STD_LOGIC;
        lineBuffer_val_V_1_i_d0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        lineBuffer_val_V_1_i_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_1_i_ce1 : OUT STD_LOGIC;
        lineBuffer_val_V_1_i_q1 : IN STD_LOGIC_VECTOR (29 downto 0);
        lineBuffer_val_V_i_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_i_ce0 : OUT STD_LOGIC;
        lineBuffer_val_V_i_we0 : OUT STD_LOGIC;
        lineBuffer_val_V_i_d0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        lineBuffer_val_V_i_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_i_ce1 : OUT STD_LOGIC;
        lineBuffer_val_V_i_q1 : IN STD_LOGIC_VECTOR (29 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (10 downto 0);
        cmp202_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp58_i : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_49 : IN STD_LOGIC_VECTOR (1 downto 0);
        red_i : IN STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (1 downto 0);
        p_0_0_01072_222972317_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01072_222972317_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_01073_222952315_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01073_222952315_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_01074_222932313_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01074_222932313_i_out_ap_vld : OUT STD_LOGIC;
        p_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_010402308_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_010402308_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_010392306_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_010392306_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_010382304_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_010382304_i_out_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_01077_22249_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_01077_22249_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_01076_22246_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_01076_22246_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_01075_22243_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_01075_22243_i_out_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_010772219_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_010772219_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_010762216_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_010762216_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_010752213_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_010752213_i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_val_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (29 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;



begin
    lineBuffer_val_V_U : component design_1_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 30,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address0,
        ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce0,
        we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_we0,
        d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_d0,
        address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address1,
        ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce1,
        q1 => lineBuffer_val_V_q1);

    lineBuffer_val_V_1_U : component design_1_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 30,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address0,
        ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce0,
        we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_we0,
        d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_d0,
        address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address1,
        ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce1,
        q1 => lineBuffer_val_V_1_q1);

    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172 : component design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start,
        ap_done => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done,
        ap_idle => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_idle,
        ap_ready => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_ready,
        imgG_dout => imgG_dout,
        imgG_num_data_valid => ap_const_lv2_0,
        imgG_fifo_cap => ap_const_lv2_0,
        imgG_empty_n => imgG_empty_n,
        imgG_read => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgG_read,
        imgRB_din => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_din,
        imgRB_num_data_valid => ap_const_lv2_0,
        imgRB_fifo_cap => ap_const_lv2_0,
        imgRB_full_n => imgRB_full_n,
        imgRB_write => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_write,
        p_0_0_01072_222972316_lcssa2353_i => p_0_0_01072_222972316_lcssa2353_i_load_reg_587,
        p_0_0_01073_222952314_lcssa2351_i => p_0_0_01073_222952314_lcssa2351_i_load_reg_582,
        p_0_0_01074_222932312_lcssa2349_i => p_0_0_01074_222932312_lcssa2349_i_load_reg_577,
        p_lcssa23112347_i => p_lcssa23112347_i_load_reg_572,
        p_lcssa23102345_i => p_lcssa23102345_i_load_reg_567,
        p_lcssa23092343_i => p_lcssa23092343_i_load_reg_562,
        p_0_2_0_0_010402307_lcssa2341_i => p_0_2_0_0_010402307_lcssa2341_i_load_reg_557,
        p_0_1_0_0_010392305_lcssa2339_i => p_0_1_0_0_010392305_lcssa2339_i_load_reg_552,
        p_0_0_0_0_010382303_lcssa2337_i => p_0_0_0_0_010382303_lcssa2337_i_load_reg_547,
        p_0_2_0_0_01077_22250_lcssa2282_i => p_0_2_0_0_01077_22250_lcssa2282_i_load_reg_542,
        p_0_1_0_0_01076_22247_lcssa2280_i => p_0_1_0_0_01076_22247_lcssa2280_i_load_reg_537,
        p_0_0_0_0_01075_22244_lcssa2278_i => p_0_0_0_0_01075_22244_lcssa2278_i_load_reg_532,
        p_0_2_0_0_010772220_lcssa2270_i => p_0_2_0_0_010772220_lcssa2270_i_load_reg_527,
        p_0_1_0_0_010762217_lcssa2268_i => p_0_1_0_0_010762217_lcssa2268_i_load_reg_522,
        p_0_0_0_0_010752214_lcssa2266_i => p_0_0_0_0_010752214_lcssa2266_i_load_reg_517,
        add_ln585_i => add_ln585_reg_504,
        out_y_i => out_y_i_reg_607,
        x_phase_i => x_phase_reg_493,
        xor_i => xor_i_reg_612,
        lineBuffer_val_V_1_i_address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address0,
        lineBuffer_val_V_1_i_ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce0,
        lineBuffer_val_V_1_i_we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_we0,
        lineBuffer_val_V_1_i_d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_d0,
        lineBuffer_val_V_1_i_address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address1,
        lineBuffer_val_V_1_i_ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce1,
        lineBuffer_val_V_1_i_q1 => lineBuffer_val_V_1_q1,
        lineBuffer_val_V_i_address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address0,
        lineBuffer_val_V_i_ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce0,
        lineBuffer_val_V_i_we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_we0,
        lineBuffer_val_V_i_d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_d0,
        lineBuffer_val_V_i_address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address1,
        lineBuffer_val_V_i_ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce1,
        lineBuffer_val_V_i_q1 => lineBuffer_val_V_q1,
        trunc_ln => width,
        cmp202_i => cmp202_i_reg_602,
        cmp58_i => cmp58_i_reg_597,
        empty_49 => empty_128_reg_627,
        red_i => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_red_i,
        empty => empty_127_reg_622,
        p_0_0_01072_222972317_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out,
        p_0_0_01072_222972317_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out_ap_vld,
        p_0_0_01073_222952315_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out,
        p_0_0_01073_222952315_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out_ap_vld,
        p_0_0_01074_222932313_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out,
        p_0_0_01074_222932313_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out_ap_vld,
        p_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out,
        p_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out_ap_vld,
        p_out1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1,
        p_out1_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1_ap_vld,
        p_out2 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2,
        p_out2_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2_ap_vld,
        p_0_2_0_0_010402308_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out,
        p_0_2_0_0_010402308_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out_ap_vld,
        p_0_1_0_0_010392306_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out,
        p_0_1_0_0_010392306_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out_ap_vld,
        p_0_0_0_0_010382304_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out,
        p_0_0_0_0_010382304_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out_ap_vld,
        p_0_2_0_0_01077_22249_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out,
        p_0_2_0_0_01077_22249_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out_ap_vld,
        p_0_1_0_0_01076_22246_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out,
        p_0_1_0_0_01076_22246_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out_ap_vld,
        p_0_0_0_0_01075_22243_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out,
        p_0_0_0_0_01075_22243_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out_ap_vld,
        p_0_2_0_0_010772219_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out,
        p_0_2_0_0_010772219_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out_ap_vld,
        p_0_1_0_0_010762216_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out,
        p_0_1_0_0_010762216_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out_ap_vld,
        p_0_0_0_0_010752213_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out,
        p_0_0_0_0_010752213_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln585_fu_260_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((bayerPhase_c_full_n = ap_const_logic_0) or (bayerPhase_c9_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_74 <= ap_const_lv11_0;
            elsif (((icmp_ln585_fu_260_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_74 <= y_4_fu_265_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln585_reg_504 <= add_ln585_fu_242_p2;
                loopHeight_reg_488 <= loopHeight_fu_222_p2;
                trunc_ln577_1_i_reg_498 <= bayerPhase_c9_dout(15 downto 1);
                x_phase_reg_493 <= x_phase_fu_228_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln585_fu_260_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                cmp202_i_reg_602 <= cmp202_i_fu_325_p2;
                cmp58_i_reg_597 <= cmp58_i_fu_320_p2;
                empty_126_reg_592 <= empty_126_fu_316_p1;
                p_0_0_01072_222972316_lcssa2353_i_load_reg_587 <= p_0_0_01072_222972316_lcssa2353_i_fu_134;
                p_0_0_01073_222952314_lcssa2351_i_load_reg_582 <= p_0_0_01073_222952314_lcssa2351_i_fu_130;
                p_0_0_01074_222932312_lcssa2349_i_load_reg_577 <= p_0_0_01074_222932312_lcssa2349_i_fu_126;
                p_0_0_0_0_010382303_lcssa2337_i_load_reg_547 <= p_0_0_0_0_010382303_lcssa2337_i_fu_102;
                p_0_0_0_0_010752214_lcssa2266_i_load_reg_517 <= p_0_0_0_0_010752214_lcssa2266_i_fu_78;
                p_0_0_0_0_01075_22244_lcssa2278_i_load_reg_532 <= p_0_0_0_0_01075_22244_lcssa2278_i_fu_90;
                p_0_1_0_0_010392305_lcssa2339_i_load_reg_552 <= p_0_1_0_0_010392305_lcssa2339_i_fu_106;
                p_0_1_0_0_010762217_lcssa2268_i_load_reg_522 <= p_0_1_0_0_010762217_lcssa2268_i_fu_82;
                p_0_1_0_0_01076_22247_lcssa2280_i_load_reg_537 <= p_0_1_0_0_01076_22247_lcssa2280_i_fu_94;
                p_0_2_0_0_010402307_lcssa2341_i_load_reg_557 <= p_0_2_0_0_010402307_lcssa2341_i_fu_110;
                p_0_2_0_0_010772220_lcssa2270_i_load_reg_527 <= p_0_2_0_0_010772220_lcssa2270_i_fu_86;
                p_0_2_0_0_01077_22250_lcssa2282_i_load_reg_542 <= p_0_2_0_0_01077_22250_lcssa2282_i_fu_98;
                p_lcssa23092343_i_load_reg_562 <= p_lcssa23092343_i_fu_114;
                p_lcssa23102345_i_load_reg_567 <= p_lcssa23102345_i_fu_118;
                p_lcssa23112347_i_load_reg_572 <= p_lcssa23112347_i_fu_122;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    empty_127_reg_622(1) <= empty_127_fu_363_p3(1);
                    empty_128_reg_627(1) <= empty_128_fu_372_p3(1);
                out_y_i_reg_607 <= out_y_i_fu_336_p2;
                red_i_reg_617 <= red_i_fu_357_p2;
                xor_i_reg_612 <= xor_i_fu_351_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_01072_222972316_lcssa2353_i_fu_134 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_01073_222952314_lcssa2351_i_fu_130 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_01074_222932312_lcssa2349_i_fu_126 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_010382303_lcssa2337_i_fu_102 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_010752214_lcssa2266_i_fu_78 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_01075_22244_lcssa2278_i_fu_90 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_010392305_lcssa2339_i_fu_106 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_010762217_lcssa2268_i_fu_82 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_01076_22247_lcssa2280_i_fu_94 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_010402307_lcssa2341_i_fu_110 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_010772220_lcssa2270_i_fu_86 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_01077_22250_lcssa2282_i_fu_98 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa23092343_i_fu_114 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa23102345_i_fu_118 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa23112347_i_fu_122 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    zext_ln585_reg_509(10 downto 0) <= zext_ln585_fu_256_p1(10 downto 0);
            end if;
        end if;
    end process;
    zext_ln585_reg_509(11) <= '0';
    empty_127_reg_622(0) <= '0';
    empty_128_reg_627(0) <= '0';

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, bayerPhase_c9_empty_n, bayerPhase_c_full_n, ap_CS_fsm_state2, icmp_ln585_fu_260_p2, grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((bayerPhase_c_full_n = ap_const_logic_0) or (bayerPhase_c9_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln585_fu_260_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln585_fu_242_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv11_1));
    and309_cast_i_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_y_cast_i_fu_342_p2),15));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, bayerPhase_c9_empty_n, bayerPhase_c_full_n)
    begin
        if (((bayerPhase_c_full_n = ap_const_logic_0) or (bayerPhase_c9_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done)
    begin
        if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, bayerPhase_c9_empty_n, bayerPhase_c_full_n)
    begin
                ap_block_state1 <= ((bayerPhase_c_full_n = ap_const_logic_0) or (bayerPhase_c9_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln585_fu_260_p2)
    begin
        if (((icmp_ln585_fu_260_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bayerPhase_c9_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c9_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c9_blk_n <= bayerPhase_c9_empty_n;
        else 
            bayerPhase_c9_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bayerPhase_c9_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c9_empty_n, bayerPhase_c_full_n)
    begin
        if ((not(((bayerPhase_c_full_n = ap_const_logic_0) or (bayerPhase_c9_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c9_read <= ap_const_logic_1;
        else 
            bayerPhase_c9_read <= ap_const_logic_0;
        end if; 
    end process;


    bayerPhase_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c_blk_n <= bayerPhase_c_full_n;
        else 
            bayerPhase_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bayerPhase_c_din <= bayerPhase_c9_dout;

    bayerPhase_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c9_empty_n, bayerPhase_c_full_n)
    begin
        if ((not(((bayerPhase_c_full_n = ap_const_logic_0) or (bayerPhase_c9_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c_write <= ap_const_logic_1;
        else 
            bayerPhase_c_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp202_i_fu_325_p2 <= "0" when (y_fu_74 = ap_const_lv11_0) else "1";
    cmp58_i_fu_320_p2 <= "1" when (unsigned(y_fu_74) < unsigned(height)) else "0";
    empty_126_fu_316_p1 <= y_fu_74(1 - 1 downto 0);
    empty_127_fu_363_p3 <= 
        ap_const_lv2_0 when (red_i_fu_357_p2(0) = '1') else 
        ap_const_lv2_2;
    empty_128_fu_372_p3 <= 
        ap_const_lv2_2 when (red_i_fu_357_p2(0) = '1') else 
        ap_const_lv2_0;
    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg;
    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_red_i <= red_i_reg_617(0);
    icmp_ln585_fu_260_p2 <= "1" when (y_fu_74 = loopHeight_reg_488) else "0";

    imgG_read_assign_proc : process(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgG_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            imgG_read <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgG_read;
        else 
            imgG_read <= ap_const_logic_0;
        end if; 
    end process;

    imgRB_din <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_din;

    imgRB_write_assign_proc : process(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            imgRB_write <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_write;
        else 
            imgRB_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln585_fu_260_p2)
    begin
        if (((icmp_ln585_fu_260_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_fu_222_p2 <= std_logic_vector(unsigned(height) + unsigned(ap_const_lv11_1));
    out_y_cast_i_fu_342_p2 <= (empty_126_reg_592 xor ap_const_lv1_1);
    out_y_i_fu_336_p2 <= std_logic_vector(unsigned(zext_ln585_reg_509) + unsigned(ap_const_lv12_FFF));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    red_i_fu_357_p2 <= "1" when (and309_cast_i_fu_347_p1 = trunc_ln577_1_i_reg_498) else "0";
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    x_phase_fu_228_p1 <= bayerPhase_c9_dout(1 - 1 downto 0);
    xor_i_fu_351_p2 <= (trunc_ln577_1_i_reg_498 xor and309_cast_i_fu_347_p1);
    y_4_fu_265_p2 <= std_logic_vector(unsigned(y_fu_74) + unsigned(ap_const_lv11_1));
    zext_ln585_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_74),12));
end behav;
