-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_demosaic_0_0_DebayerRandBatG is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    imgRB_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    imgRB_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgRB_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgRB_empty_n : IN STD_LOGIC;
    imgRB_read : OUT STD_LOGIC;
    imgRgb_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    imgRgb_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    imgRgb_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    imgRgb_full_n : IN STD_LOGIC;
    imgRgb_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (10 downto 0);
    width : IN STD_LOGIC_VECTOR (10 downto 0);
    bayerPhase_c_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    bayerPhase_c_empty_n : IN STD_LOGIC;
    bayerPhase_c_read : OUT STD_LOGIC );
end;


architecture behav of design_1_v_demosaic_0_0_DebayerRandBatG is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bayerPhase_c_blk_n : STD_LOGIC;
    signal loopHeight_fu_185_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopHeight_reg_400 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_phase_fu_191_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_reg_405 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln825_1_i_reg_410 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln833_fu_205_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln833_reg_415 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln833_fu_219_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln833_reg_420 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_0_0_0_0_01231_12329_lcssa2371_i_load_reg_428 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln833_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_1_0_0_01232_12332_lcssa2373_i_load_reg_433 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_01233_12335_lcssa2375_i_load_reg_438 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa24082442_i_load_reg_443 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa24092444_i_load_reg_448 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa24102446_i_load_reg_453 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_011942411_lcssa2448_i_load_reg_458 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_011952413_lcssa2450_i_load_reg_463 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_011962415_lcssa2452_i_load_reg_468 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01230_223982418_lcssa2454_i_load_reg_473 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01229_224002420_lcssa2456_i_load_reg_478 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01228_224022422_lcssa2458_i_load_reg_483 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_i_fu_284_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_i_reg_488 : STD_LOGIC_VECTOR (14 downto 0);
    signal cmp58_i_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp58_i_reg_493 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp202_i_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp202_i_reg_498 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_y_i_fu_305_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal out_y_i_reg_503 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal lineBuffer_val_V_q1 : STD_LOGIC_VECTOR (29 downto 0);
    signal lineBuffer_val_V_2_q1 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_idle : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_ready : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRB_read : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_write : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce0 : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_we0 : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_d0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce1 : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce0 : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_we0 : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_d0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce1 : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_0_01228_224022422_lcssa2458_i_fu_114 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01229_224002420_lcssa2456_i_fu_110 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01230_223982418_lcssa2454_i_fu_106 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_011962415_lcssa2452_i_fu_102 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_011952413_lcssa2450_i_fu_98 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_011942411_lcssa2448_i_fu_94 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa24102446_i_fu_90 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa24092444_i_fu_86 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa24082442_i_fu_82 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_01233_12335_lcssa2375_i_fu_78 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_01232_12332_lcssa2373_i_fu_74 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_01231_12329_lcssa2371_i_fu_70 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_66 : STD_LOGIC_VECTOR (10 downto 0);
    signal y_6_fu_228_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal empty_130_fu_270_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_y_cast_i_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and305_cast_i_fu_280_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgRB_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        imgRB_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgRB_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgRB_empty_n : IN STD_LOGIC;
        imgRB_read : OUT STD_LOGIC;
        imgRgb_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        imgRgb_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        imgRgb_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        imgRgb_full_n : IN STD_LOGIC;
        imgRgb_write : OUT STD_LOGIC;
        p_0_0_01228_224022422_lcssa2458_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01229_224002420_lcssa2456_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01230_223982418_lcssa2454_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_011962415_lcssa2452_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_011952413_lcssa2450_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_011942411_lcssa2448_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa24102446_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa24092444_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa24082442_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_01233_12335_lcssa2375_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_01232_12332_lcssa2373_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_01231_12329_lcssa2371_i : IN STD_LOGIC_VECTOR (9 downto 0);
        add_ln833_i : IN STD_LOGIC_VECTOR (10 downto 0);
        x_phase_i : IN STD_LOGIC_VECTOR (0 downto 0);
        xor_i : IN STD_LOGIC_VECTOR (14 downto 0);
        out_y_i : IN STD_LOGIC_VECTOR (11 downto 0);
        lineBuffer_val_V_2_i_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_2_i_ce0 : OUT STD_LOGIC;
        lineBuffer_val_V_2_i_we0 : OUT STD_LOGIC;
        lineBuffer_val_V_2_i_d0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        lineBuffer_val_V_2_i_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_2_i_ce1 : OUT STD_LOGIC;
        lineBuffer_val_V_2_i_q1 : IN STD_LOGIC_VECTOR (29 downto 0);
        lineBuffer_val_V_i_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_i_ce0 : OUT STD_LOGIC;
        lineBuffer_val_V_i_we0 : OUT STD_LOGIC;
        lineBuffer_val_V_i_d0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        lineBuffer_val_V_i_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        lineBuffer_val_V_i_ce1 : OUT STD_LOGIC;
        lineBuffer_val_V_i_q1 : IN STD_LOGIC_VECTOR (29 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (10 downto 0);
        cmp202_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp58_i : IN STD_LOGIC_VECTOR (0 downto 0);
        p_0_0_01228_224022421_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01228_224022421_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_01229_224002419_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01229_224002419_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_01230_223982417_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01230_223982417_i_out_ap_vld : OUT STD_LOGIC;
        right_val_V_2_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        right_val_V_2_i_out_ap_vld : OUT STD_LOGIC;
        right_val_V_1_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        right_val_V_1_i_out_ap_vld : OUT STD_LOGIC;
        right_val_V_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        right_val_V_i_out_ap_vld : OUT STD_LOGIC;
        p_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_01233_12334_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_01233_12334_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_01232_12331_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_01232_12331_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_01231_12328_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_01231_12328_i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_demosaic_0_0_DebayerRandBatG_lineBuffer_val_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (29 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;



begin
    lineBuffer_val_V_U : component design_1_v_demosaic_0_0_DebayerRandBatG_lineBuffer_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 30,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address0,
        ce0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce0,
        we0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_we0,
        d0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_d0,
        address1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address1,
        ce1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce1,
        q1 => lineBuffer_val_V_q1);

    lineBuffer_val_V_2_U : component design_1_v_demosaic_0_0_DebayerRandBatG_lineBuffer_val_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 30,
        AddressRange => 1921,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address0,
        ce0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce0,
        we0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_we0,
        d0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_d0,
        address1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address1,
        ce1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce1,
        q1 => lineBuffer_val_V_2_q1);

    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144 : component design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start,
        ap_done => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done,
        ap_idle => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_idle,
        ap_ready => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_ready,
        imgRB_dout => imgRB_dout,
        imgRB_num_data_valid => ap_const_lv2_0,
        imgRB_fifo_cap => ap_const_lv2_0,
        imgRB_empty_n => imgRB_empty_n,
        imgRB_read => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRB_read,
        imgRgb_din => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_din,
        imgRgb_num_data_valid => ap_const_lv2_0,
        imgRgb_fifo_cap => ap_const_lv2_0,
        imgRgb_full_n => imgRgb_full_n,
        imgRgb_write => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_write,
        p_0_0_01228_224022422_lcssa2458_i => p_0_0_01228_224022422_lcssa2458_i_load_reg_483,
        p_0_0_01229_224002420_lcssa2456_i => p_0_0_01229_224002420_lcssa2456_i_load_reg_478,
        p_0_0_01230_223982418_lcssa2454_i => p_0_0_01230_223982418_lcssa2454_i_load_reg_473,
        p_0_2_0_0_011962415_lcssa2452_i => p_0_2_0_0_011962415_lcssa2452_i_load_reg_468,
        p_0_1_0_0_011952413_lcssa2450_i => p_0_1_0_0_011952413_lcssa2450_i_load_reg_463,
        p_0_0_0_0_011942411_lcssa2448_i => p_0_0_0_0_011942411_lcssa2448_i_load_reg_458,
        p_lcssa24102446_i => p_lcssa24102446_i_load_reg_453,
        p_lcssa24092444_i => p_lcssa24092444_i_load_reg_448,
        p_lcssa24082442_i => p_lcssa24082442_i_load_reg_443,
        p_0_2_0_0_01233_12335_lcssa2375_i => p_0_2_0_0_01233_12335_lcssa2375_i_load_reg_438,
        p_0_1_0_0_01232_12332_lcssa2373_i => p_0_1_0_0_01232_12332_lcssa2373_i_load_reg_433,
        p_0_0_0_0_01231_12329_lcssa2371_i => p_0_0_0_0_01231_12329_lcssa2371_i_load_reg_428,
        add_ln833_i => add_ln833_reg_415,
        x_phase_i => x_phase_reg_405,
        xor_i => xor_i_reg_488,
        out_y_i => out_y_i_reg_503,
        lineBuffer_val_V_2_i_address0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address0,
        lineBuffer_val_V_2_i_ce0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce0,
        lineBuffer_val_V_2_i_we0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_we0,
        lineBuffer_val_V_2_i_d0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_d0,
        lineBuffer_val_V_2_i_address1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address1,
        lineBuffer_val_V_2_i_ce1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce1,
        lineBuffer_val_V_2_i_q1 => lineBuffer_val_V_2_q1,
        lineBuffer_val_V_i_address0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address0,
        lineBuffer_val_V_i_ce0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce0,
        lineBuffer_val_V_i_we0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_we0,
        lineBuffer_val_V_i_d0 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_d0,
        lineBuffer_val_V_i_address1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address1,
        lineBuffer_val_V_i_ce1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce1,
        lineBuffer_val_V_i_q1 => lineBuffer_val_V_q1,
        trunc_ln => width,
        cmp202_i => cmp202_i_reg_498,
        cmp58_i => cmp58_i_reg_493,
        p_0_0_01228_224022421_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out,
        p_0_0_01228_224022421_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out_ap_vld,
        p_0_0_01229_224002419_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out,
        p_0_0_01229_224002419_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out_ap_vld,
        p_0_0_01230_223982417_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out,
        p_0_0_01230_223982417_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out_ap_vld,
        right_val_V_2_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out,
        right_val_V_2_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out_ap_vld,
        right_val_V_1_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out,
        right_val_V_1_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out_ap_vld,
        right_val_V_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out,
        right_val_V_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out_ap_vld,
        p_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out,
        p_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out_ap_vld,
        p_out1 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1,
        p_out1_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1_ap_vld,
        p_out2 => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2,
        p_out2_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2_ap_vld,
        p_0_2_0_0_01233_12334_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out,
        p_0_2_0_0_01233_12334_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out_ap_vld,
        p_0_1_0_0_01232_12331_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out,
        p_0_1_0_0_01232_12331_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out_ap_vld,
        p_0_0_0_0_01231_12328_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out,
        p_0_0_0_0_01231_12328_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln833_fu_223_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (bayerPhase_c_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_66 <= ap_const_lv11_0;
            elsif (((icmp_ln833_fu_223_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_66 <= y_6_fu_228_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln833_reg_415 <= add_ln833_fu_205_p2;
                loopHeight_reg_400 <= loopHeight_fu_185_p2;
                trunc_ln825_1_i_reg_410 <= bayerPhase_c_dout(15 downto 1);
                x_phase_reg_405 <= x_phase_fu_191_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln833_fu_223_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                cmp202_i_reg_498 <= cmp202_i_fu_294_p2;
                cmp58_i_reg_493 <= cmp58_i_fu_289_p2;
                p_0_0_01228_224022422_lcssa2458_i_load_reg_483 <= p_0_0_01228_224022422_lcssa2458_i_fu_114;
                p_0_0_01229_224002420_lcssa2456_i_load_reg_478 <= p_0_0_01229_224002420_lcssa2456_i_fu_110;
                p_0_0_01230_223982418_lcssa2454_i_load_reg_473 <= p_0_0_01230_223982418_lcssa2454_i_fu_106;
                p_0_0_0_0_011942411_lcssa2448_i_load_reg_458 <= p_0_0_0_0_011942411_lcssa2448_i_fu_94;
                p_0_0_0_0_01231_12329_lcssa2371_i_load_reg_428 <= p_0_0_0_0_01231_12329_lcssa2371_i_fu_70;
                p_0_1_0_0_011952413_lcssa2450_i_load_reg_463 <= p_0_1_0_0_011952413_lcssa2450_i_fu_98;
                p_0_1_0_0_01232_12332_lcssa2373_i_load_reg_433 <= p_0_1_0_0_01232_12332_lcssa2373_i_fu_74;
                p_0_2_0_0_011962415_lcssa2452_i_load_reg_468 <= p_0_2_0_0_011962415_lcssa2452_i_fu_102;
                p_0_2_0_0_01233_12335_lcssa2375_i_load_reg_438 <= p_0_2_0_0_01233_12335_lcssa2375_i_fu_78;
                p_lcssa24082442_i_load_reg_443 <= p_lcssa24082442_i_fu_82;
                p_lcssa24092444_i_load_reg_448 <= p_lcssa24092444_i_fu_86;
                p_lcssa24102446_i_load_reg_453 <= p_lcssa24102446_i_fu_90;
                xor_i_reg_488 <= xor_i_fu_284_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                out_y_i_reg_503 <= out_y_i_fu_305_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_01228_224022422_lcssa2458_i_fu_114 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_01229_224002420_lcssa2456_i_fu_110 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_01230_223982418_lcssa2454_i_fu_106 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_011942411_lcssa2448_i_fu_94 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_01231_12329_lcssa2371_i_fu_70 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out_ap_vld = ap_const_logic_1))) then
                p_0_1_0_0_011952413_lcssa2450_i_fu_98 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_01232_12332_lcssa2373_i_fu_74 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out_ap_vld = ap_const_logic_1))) then
                p_0_2_0_0_011962415_lcssa2452_i_fu_102 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_01233_12335_lcssa2375_i_fu_78 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa24082442_i_fu_82 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1_ap_vld = ap_const_logic_1))) then
                p_lcssa24092444_i_fu_86 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out_ap_vld = ap_const_logic_1))) then
                p_lcssa24102446_i_fu_90 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    zext_ln833_reg_420(10 downto 0) <= zext_ln833_fu_219_p1(10 downto 0);
            end if;
        end if;
    end process;
    zext_ln833_reg_420(11) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, bayerPhase_c_empty_n, ap_CS_fsm_state2, icmp_ln833_fu_223_p2, grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (bayerPhase_c_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln833_fu_223_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln833_fu_205_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv11_1));
    and305_cast_i_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_y_cast_i_fu_274_p2),15));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, bayerPhase_c_empty_n)
    begin
        if (((ap_start = ap_const_logic_0) or (bayerPhase_c_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done)
    begin
        if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, bayerPhase_c_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (bayerPhase_c_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln833_fu_223_p2)
    begin
        if (((icmp_ln833_fu_223_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln833_fu_223_p2)
    begin
        if (((icmp_ln833_fu_223_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bayerPhase_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c_blk_n <= bayerPhase_c_empty_n;
        else 
            bayerPhase_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bayerPhase_c_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (bayerPhase_c_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c_read <= ap_const_logic_1;
        else 
            bayerPhase_c_read <= ap_const_logic_0;
        end if; 
    end process;

    cmp202_i_fu_294_p2 <= "0" when (y_fu_66 = ap_const_lv11_0) else "1";
    cmp58_i_fu_289_p2 <= "1" when (unsigned(y_fu_66) < unsigned(height)) else "0";
    empty_130_fu_270_p1 <= y_fu_66(1 - 1 downto 0);
    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg;
    icmp_ln833_fu_223_p2 <= "1" when (y_fu_66 = loopHeight_reg_400) else "0";

    imgRB_read_assign_proc : process(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRB_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            imgRB_read <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRB_read;
        else 
            imgRB_read <= ap_const_logic_0;
        end if; 
    end process;

    imgRgb_din <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_din;

    imgRgb_write_assign_proc : process(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            imgRgb_write <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_write;
        else 
            imgRgb_write <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_fu_185_p2 <= std_logic_vector(unsigned(height) + unsigned(ap_const_lv11_1));
    out_y_cast_i_fu_274_p2 <= (empty_130_fu_270_p1 xor ap_const_lv1_1);
    out_y_i_fu_305_p2 <= std_logic_vector(unsigned(zext_ln833_reg_420) + unsigned(ap_const_lv12_FFF));
    x_phase_fu_191_p1 <= bayerPhase_c_dout(1 - 1 downto 0);
    xor_i_fu_284_p2 <= (trunc_ln825_1_i_reg_410 xor and305_cast_i_fu_280_p1);
    y_6_fu_228_p2 <= std_logic_vector(unsigned(y_fu_66) + unsigned(ap_const_lv11_1));
    zext_ln833_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_66),12));
end behav;
